name: f_glitch
description: >
  Add glitch effect and RGB shift effect to selected image and
  change frequency of occurrence to these effects.
version: 0.1.2
homepage: https://github.com/kyu-suke/f_glitch

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
